# Derived from impresso_ensemble_lid.py run logged on 2025-09-04 02:29:35



LANGIDENT_LID_SYSTEMS_OPTION := langid impresso_ft wp_ft impresso_langident_pipeline lingua
LANGIDENT_ENSEMBLE_WEIGHT_LB_IMPRESSO_OPTION := 3.0
LANGIDENT_ENSEMBLE_MINIMAL_LID_PROBABILITY_OPTION := 0.5
LANGIDENT_ENSEMBLE_MINIMAL_TEXT_LENGTH_OPTION := 50
LANGIDENT_SYSTEMS_ALPHABETICAL_THRESHOLD_OPTION := 0.5
LANGIDENT_ENSEMBLE_MINIMAL_VOTING_SCORE_OPTION := 0.5
LANGIDENT_ENSEMBLE_THRESHOLD_CONFIDENCE_ORIG_LG_OPTION := 0.75
LANGIDENT_ENSEMBLE_DOMINANT_LANGUAGE_THRESHOLD_OPTION := 0.9

# Additional configuration options with defaults
LANGIDENT_ROUND_NDIGITS_OPTION := 3
LANGIDENT_DEBUG_OPTION := 
LANGIDENT_VALIDATE_OPTION := --validate
LANGIDENT_ADMISSIBLE_LANGUAGES_OPTION := 
LANGIDENT_EXCLUDE_LB_OPTION := 
LANGIDENT_MINIMAL_VOTE_SCORE_OPTION := 0.5
LANGIDENT_SYSTEMS_MINIMAL_LID_PROBABILITY_OPTION := 0.5
# no LB
# BCUL BL BNF FedGaz LeTemps NZZ SNL SWA SWISSINFO
