# Derived from config-langidentocrqa_canonical-lid-ensemble_multilingual_v2-0-2.mk
# Adds canonical pages/audios auto-selection for newspaper and radio collections.
USE_CANONICAL ?= 1
NEWSPAPER_HAS_PROVIDER ?= 1
CANONICAL_INPUT_KIND ?= auto

# requires setup if active
LANGIDENT_LOCAL_FILES_ONLY_OPTION ?= --local-files-only
NEWSPAPER_JOBS=6

# Default canonical bucket for production canonical data.
# Override with S3_BUCKET_CANONICAL=111-canonical-staging for staging radio tests.
S3_BUCKET_CANONICAL ?= 111-canonical-staging
S3_PREFIX_NEWSPAPERS_TO_PROCESS_BUCKET ?= $(S3_BUCKET_CANONICAL)
S3_BUCKET_LANGIDENT_STAGE1 ?= 114-canonical-processed-staging
S3_BUCKET_LANGIDENT ?= 114-canonical-processed-staging

RUN_VERSION_LANGIDENT ?= v2-0-3
CONSOLIDATEDCANONICAL_VALIDATE_OPTION ?= --validate
LANGIDENT_UPLOAD_IF_NEWER_OPTION ?=
#LANGIDENT_UPLOAD_IF_NEWER_OPTION ?= --upload-if-newer

# Base LID systems (always included)
LANGIDENT_SYSTEMS_LIDS_BASE ?= langid wp_ft lingua
LANGIDENT_SYSTEMS_LIDS_EXTRA_DEFAULT ?= impresso_langident_pipeline

# Provider-specific additional systems (only non-default providers listed)
LANGIDENT_SYSTEMS_LIDS_EXTRA_BL ?=
LANGIDENT_SYSTEMS_LIDS_EXTRA_BNF ?=
LANGIDENT_SYSTEMS_LIDS_EXTRA_BNL ?= impresso_ft impresso_langident_pipeline

LANGIDENT_SYSTEMS_LIDS_EXTRA_RTS ?= $(LANGIDENT_SYSTEMS_LIDS_EXTRA_DEFAULT)
LANGIDENT_SYSTEMS_LIDS_EXTRA_SWA ?= $(LANGIDENT_SYSTEMS_LIDS_EXTRA_DEFAULT)
LANGIDENT_SYSTEMS_LIDS_EXTRA_SNL ?= $(LANGIDENT_SYSTEMS_LIDS_EXTRA_DEFAULT)
LANGIDENT_SYSTEMS_LIDS_EXTRA_BCUL ?= $(LANGIDENT_SYSTEMS_LIDS_EXTRA_DEFAULT)
LANGIDENT_SYSTEMS_LIDS_EXTRA_LeTemps ?= $(LANGIDENT_SYSTEMS_LIDS_EXTRA_DEFAULT)
LANGIDENT_SYSTEMS_LIDS_EXTRA_NZZ ?= $(LANGIDENT_SYSTEMS_LIDS_EXTRA_DEFAULT)
LANGIDENT_SYSTEMS_LIDS_EXTRA_SWISSINFO ?= $(LANGIDENT_SYSTEMS_LIDS_EXTRA_DEFAULT)
LANGIDENT_SYSTEMS_LIDS_EXTRA_SUB ?= $(LANGIDENT_SYSTEMS_LIDS_EXTRA_DEFAULT)

# Extract provider prefix and lookup additional systems.
# Supports both NEWSPAPER=PROVIDER/TITLE and PROVIDER=... NEWSPAPER=TITLE.
NEWSPAPER_PROVIDER = $(if $(PROVIDER),$(PROVIDER),$(firstword $(subst /, ,$(NEWSPAPER))))
LANGIDENT_SYSTEMS_LIDS_EXTRA = $(or \
  $(LANGIDENT_SYSTEMS_LIDS_EXTRA_$(NEWSPAPER_PROVIDER)),\
  $(LANGIDENT_SYSTEMS_LIDS_EXTRA_DEFAULT))

LANGIDENT_SYSTEMS_LIDS_OPTION ?= $(LANGIDENT_SYSTEMS_LIDS_BASE) $(LANGIDENT_SYSTEMS_LIDS_EXTRA)

LANGIDENT_ENSEMBLE_WEIGHT_LB_IMPRESSO_OPTION ?= 3.0
LANGIDENT_ENSEMBLE_MINIMAL_LID_PROBABILITY_OPTION ?= 0.5
LANGIDENT_ENSEMBLE_MINIMAL_TEXT_LENGTH_OPTION ?= 50
LANGIDENT_SYSTEMS_ALPHABETICAL_THRESHOLD_OPTION ?= 0.5
LANGIDENT_ENSEMBLE_MINIMAL_VOTING_SCORE_OPTION ?= 0.5
LANGIDENT_ENSEMBLE_THRESHOLD_CONFIDENCE_ORIG_LG_OPTION ?= 0.75
LANGIDENT_ENSEMBLE_DOMINANT_LANGUAGE_THRESHOLD_OPTION ?= 0.9

# Additional configuration options with defaults
LANGIDENT_ROUND_NDIGITS_OPTION ?= 3
LANGIDENT_DEBUG_OPTION ?=
LANGIDENT_VALIDATE_OPTION ?= --validate
LANGIDENT_ADMISSIBLE_LANGUAGES_OPTION ?=
LANGIDENT_EXCLUDE_LB_OPTION ?=
LANGIDENT_MINIMAL_VOTE_SCORE_OPTION ?= 0.5
LANGIDENT_SYSTEMS_MINIMAL_LID_PROBABILITY_OPTION ?= 0.5

# No LB in the following data providers.
# RTS radio data is excluded from Luxembourgish predictions by default.
LANGIDENT_ENSEMBLE_EXCLUDE_LB_OPTION ?= BCUL/ BL/ BNF/ FedGaz/ LeTemps/ NZZ/ RTS/ SNL/ SWA/ SWISSINFO/ SUB/

LANGIDENT_OCRQA_OPTION ?= --ocrqa
LANGIDENT_OCRQA_REPO_OPTION ?= impresso-project/OCR-quality-assessment-unigram
LANGIDENT_OCRQA_VERSION_OPTION ?= main
MAKE_SILENCE_RECIPE ?=

# The following should be set in the .env as they are machine specific
#PARALLEL_DELAY ?= 1
#COLLECTION_JOBS ?= 1
#NEWSPAPER_JOBS ?= 8
#MAX_LOAD ?= 10
