# Derived from impresso_ensemble_lid.py run logged on 2025-09-04 02:29:35
USE_CANONICAL ?= 1
NEWSPAPER_HAS_PROVIDER ?= 1
NEWSPAPER_JOBS=6
# NEWSPAPER_FNMATCH ?= LeTemps/*
S3_BUCKET_CANONICAL ?= 112-canonical-final
S3_PREFIX_NEWSPAPERS_TO_PROCESS_BUCKET ?= $(S3_BUCKET_CANONICAL)
S3_BUCKET_LANGIDENT_STAGE1 ?= 115-canonical-processed-final
S3_BUCKET_LANGIDENT ?= 115-canonical-processed-final
#NEWSPAPER ?= BL/AATA
RUN_VERSION_LANGIDENT ?= v2-0-2
CONSOLIDATEDCANONICAL_VALIDATE_OPTION ?= --validate

# FOR BL we do not use impresso_langident_pipeline for the moment as English coverage is
# bad
# Also we only include impresso_ft for BNL newspapers (luxembourgish newspaper)

# Base LID systems (always included)
LANGIDENT_SYSTEMS_LIDS_BASE ?= langid wp_ft lingua

# Provider-specific additional systems (only non-default providers listed)
LANGIDENT_SYSTEMS_LIDS_EXTRA_BL ?= 
LANGIDENT_SYSTEMS_LIDS_EXTRA_BNF ?= 
LANGIDENT_SYSTEMS_LIDS_EXTRA_BNL ?= impresso_ft impresso_langident_pipeline
LANGIDENT_SYSTEMS_LIDS_EXTRA_DEFAULT ?= impresso_langident_pipeline

# Extract provider prefix and lookup additional systems
NEWSPAPER_PROVIDER = $(firstword $(subst /, ,$(NEWSPAPER)))
LANGIDENT_SYSTEMS_LIDS_EXTRA = $(or \
  $(LANGIDENT_SYSTEMS_LIDS_EXTRA_$(NEWSPAPER_PROVIDER)),\
  $(LANGIDENT_SYSTEMS_LIDS_EXTRA_DEFAULT))

LANGIDENT_SYSTEMS_LIDS_OPTION ?= $(LANGIDENT_SYSTEMS_LIDS_BASE) $(LANGIDENT_SYSTEMS_LIDS_EXTRA) 

LANGIDENT_ENSEMBLE_WEIGHT_LB_IMPRESSO_OPTION ?= 3.0
LANGIDENT_ENSEMBLE_MINIMAL_LID_PROBABILITY_OPTION ?= 0.5
LANGIDENT_ENSEMBLE_MINIMAL_TEXT_LENGTH_OPTION ?= 50
LANGIDENT_SYSTEMS_ALPHABETICAL_THRESHOLD_OPTION ?= 0.5
LANGIDENT_ENSEMBLE_MINIMAL_VOTING_SCORE_OPTION ?= 0.5
LANGIDENT_ENSEMBLE_THRESHOLD_CONFIDENCE_ORIG_LG_OPTION ?= 0.75
LANGIDENT_ENSEMBLE_DOMINANT_LANGUAGE_THRESHOLD_OPTION ?= 0.9

# Additional configuration options with defaults
LANGIDENT_ROUND_NDIGITS_OPTION ?= 3
LANGIDENT_DEBUG_OPTION ?= 
LANGIDENT_VALIDATE_OPTION ?= --validate
LANGIDENT_ADMISSIBLE_LANGUAGES_OPTION ?= 
LANGIDENT_EXCLUDE_LB_OPTION ?= 
LANGIDENT_MINIMAL_VOTE_SCORE_OPTION ?= 0.5
LANGIDENT_SYSTEMS_MINIMAL_LID_PROBABILITY_OPTION ?= 0.5
# no LB in the following data providers (will use fnmatch on the s3 path)
LANGIDENT_ENSEMBLE_EXCLUDE_LB_OPTION ?= BCUL/ BL/ BNF/ FedGaz/ LeTemps/ NZZ/ SNL/ SWA/ SWISSINFO/


LANGIDENT_OCRQA_OPTION ?= --ocrqa
LANGIDENT_OCRQA_REPO_OPTION ?= impresso-project/OCR-quality-assessment-unigram
LANGIDENT_OCRQA_VERSION_OPTION ?= main
MAKE_SILENCE_RECIPE ?= 

# The following should be set in the .env as they are machine specific
#PARALLEL_DELAY ?= 1
#COLLECTION_JOBS ?= 1
#NEWSPAPER_JOBS ?= 8
# MAX_LOAD ?= 10


# LOCAL_STAMP_SUFFIX ?= 
